# pylint: skip-file
BASE_PATH = "sample-files/"
EXAMPLES_PATH = "examples/"
REGRESSION_TEST_PATH = "sfz_regression_test_suite/"
SFZ_PATH = "sfz/"
XML_PATH = "sfz_xml/"
SFZ_FILE = ".sfz"
XML_FILE = ".xml"
EXAMPLE_FILES = ["example_1", "example_2"]
EXAMPLES = [
    {
        "sfz": f"{BASE_PATH}{EXAMPLES_PATH}{SFZ_PATH}{file}{SFZ_FILE}",
        "xml": f"{BASE_PATH}{EXAMPLES_PATH}{XML_PATH}{file}{XML_FILE}",
    }
    for file in EXAMPLE_FILES
]

SFZ_FILES = [
    "tests/sfz1 basic tests/01 - Amp LFO/01 - amp lfo freq",
    "tests/sfz1 basic tests/01 - Amp LFO/02 - amp lfo freq cc1 and after",
    "tests/sfz1 basic tests/01 - Amp LFO/03 - amp lfo depth",
    "tests/sfz1 basic tests/01 - Amp LFO/04 - amp lfo depth on cc",
    "tests/sfz1 basic tests/01 - Amp LFO/05 - amp lfo depth on channel aftertouch",
    "tests/sfz1 basic tests/01 - Amp LFO/06 - amp lfo delay",
    "tests/sfz1 basic tests/01 - Amp LFO/07 - amp lfo fade",
    "tests/sfz1 basic tests/02 - Pitch LFO/01 - pitch lfo freq",
    "tests/sfz1 basic tests/02 - Pitch LFO/02 - pitch lfo freq cc1 and after",
    "tests/sfz1 basic tests/02 - Pitch LFO/03 - pitch lfo depth",
    "tests/sfz1 basic tests/02 - Pitch LFO/04 - pitch lfo depth on cc",
    "tests/sfz1 basic tests/02 - Pitch LFO/05 - pitch lfo depth on channel aftertouch",
    "tests/sfz1 basic tests/02 - Pitch LFO/06 - pitch lfo delay",
    "tests/sfz1 basic tests/02 - Pitch LFO/07 - pitch lfo fade",
    "tests/sfz1 basic tests/03 - Filter LFO/01 - filter lfo freq",
    "tests/sfz1 basic tests/03 - Filter LFO/02 - filter lfo freq cc1 and after",
    "tests/sfz1 basic tests/03 - Filter LFO/03 - filter lfo depth",
    "tests/sfz1 basic tests/03 - Filter LFO/04 - filter lfo depth on cc",
    "tests/sfz1 basic tests/03 - Filter LFO/05 - filter lfo depth on channel aftertouch",
    "tests/sfz1 basic tests/03 - Filter LFO/06 - filter lfo delay",
    "tests/sfz1 basic tests/03 - Filter LFO/07 - filter lfo fade",
    "tests/sfz1 basic tests/04 - Pitch EG/01 - pitch eg delay",
    "tests/sfz1 basic tests/04 - Pitch EG/02 - pitch eg attack",
    "tests/sfz1 basic tests/04 - Pitch EG/03 - pitch eg hold",
    "tests/sfz1 basic tests/04 - Pitch EG/04 - pitch eg decay",
    "tests/sfz1 basic tests/04 - Pitch EG/05 - pitch eg release",
    "tests/sfz1 basic tests/04 - Pitch EG/06 - pitch eg all positive depth",
    "tests/sfz1 basic tests/04 - Pitch EG/07 - pitch eg all negative depth",
    "tests/sfz1 basic tests/04 - Pitch EG/08 - pitch eg all huge range",
    "tests/sfz1 basic tests/04 - Pitch EG/09 - pitch eg vel2delay",
    "tests/sfz1 basic tests/04 - Pitch EG/10 - pitch eg vel2attack",
    "tests/sfz1 basic tests/04 - Pitch EG/11 - pitch eg vel2hold",
    "tests/sfz1 basic tests/04 - Pitch EG/12 - pitch eg vel2decay",
    "tests/sfz1 basic tests/04 - Pitch EG/13 - pitch eg vel2release",
    "tests/sfz1 basic tests/05 - Filter EG/01 - filter eg delay",
    "tests/sfz1 basic tests/05 - Filter EG/02 - filter eg attack",
    "tests/sfz1 basic tests/05 - Filter EG/03 - filter eg hold",
    "tests/sfz1 basic tests/05 - Filter EG/04 - filter eg decay",
    "tests/sfz1 basic tests/05 - Filter EG/05 - filter eg release",
    "tests/sfz1 basic tests/05 - Filter EG/06 - filter eg one octave test",
    "tests/sfz1 basic tests/05 - Filter EG/07 - filter eg all",
    "tests/sfz1 basic tests/05 - Filter EG/08 - filter HPF eg all",
    "tests/sfz1 basic tests/05 - Filter EG/09 - filter eg vel2delay",
    "tests/sfz1 basic tests/05 - Filter EG/10 - filter eg vel2attack",
    "tests/sfz1 basic tests/05 - Filter EG/11 - filter eg vel2hold",
    "tests/sfz1 basic tests/05 - Filter EG/12 - filter eg vel2decay",
    "tests/sfz1 basic tests/05 - Filter EG/13 - filter eg vel2release",
    "tests/sfz1 basic tests/Unsorted/amp eg all_changedrelease",
    "tests/sfz1 basic tests/Unsorted/amp eg all",
    "tests/sfz1 basic tests/Unsorted/amp eg attack",
    "tests/sfz1 basic tests/Unsorted/amp eg decay",
    "tests/sfz1 basic tests/Unsorted/amp eg delay",
    "tests/sfz1 basic tests/Unsorted/amp eg hold",
    "tests/sfz1 basic tests/Unsorted/amp eg on release trigger",
    "tests/sfz1 basic tests/Unsorted/amp eg release",
    "tests/sfz1 basic tests/Unsorted/amp eg vel2attack",
    "tests/sfz1 basic tests/Unsorted/amp eg vel2decay",
    "tests/sfz1 basic tests/Unsorted/amp eg vel2delay",
    "tests/sfz1 basic tests/Unsorted/amp eg vel2hold",
    "tests/sfz1 basic tests/Unsorted/amp eg vel2release",
    "tests/sfz1 basic tests/Unsorted/amp key tracking negative",
    "tests/sfz1 basic tests/Unsorted/amp key tracking positive",
    "tests/sfz1 basic tests/Unsorted/amp velo tracking negative",
    "tests/sfz1 basic tests/Unsorted/amp velo tracking",
    "tests/sfz1 basic tests/Unsorted/bend down and up",
    "tests/sfz1 basic tests/Unsorted/bend step octave",
    "tests/sfz1 basic tests/Unsorted/bend step semi",
    "tests/sfz1 basic tests/Unsorted/bend step whole",
    "tests/sfz1 basic tests/Unsorted/bend two regions",
    "tests/sfz1 basic tests/Unsorted/channel",
    "tests/sfz1 basic tests/Unsorted/comments",
    "tests/sfz1 basic tests/Unsorted/count",
    "tests/sfz1 basic tests/Unsorted/effect1 - reverb (turn fx on)",
    "tests/sfz1 basic tests/Unsorted/effect2 - chorus (turn fx on)",
    "tests/sfz1 basic tests/Unsorted/eq bandwidth on cc20",
    "tests/sfz1 basic tests/Unsorted/eq freq on cc20",
    "tests/sfz1 basic tests/Unsorted/eq gain on cc20",
    "tests/sfz1 basic tests/Unsorted/eq three bands stereo",
    "tests/sfz1 basic tests/Unsorted/eq three bands",
    "tests/sfz1 basic tests/Unsorted/eq1 dynamic",
    "tests/sfz1 basic tests/Unsorted/eq1 vel2gain and vel2freq",
    "tests/sfz1 basic tests/Unsorted/eq2 dynamic",
    "tests/sfz1 basic tests/Unsorted/eq3 dynamic",
    "tests/sfz1 basic tests/Unsorted/exclusive regions bi",
    "tests/sfz1 basic tests/Unsorted/exclusive regions cut one",
    "tests/sfz1 basic tests/Unsorted/exclusive regions uni",
    "tests/sfz1 basic tests/Unsorted/filter 1p hpf",
    "tests/sfz1 basic tests/Unsorted/filter 1p lpf",
    "tests/sfz1 basic tests/Unsorted/filter 2p bpf",
    "tests/sfz1 basic tests/Unsorted/filter 2p brf",
    "tests/sfz1 basic tests/Unsorted/filter 2p hpf",
    "tests/sfz1 basic tests/Unsorted/filter 2p lpf",
    "tests/sfz1 basic tests/Unsorted/filter dynamic cutoff cc1 and channel after hpf_1p",
    "tests/sfz1 basic tests/Unsorted/filter dynamic cutoff cc1 and channel after hpf_2p",
    "tests/sfz1 basic tests/Unsorted/filter dynamic cutoff cc1 and channel after lpf_1p ",
    "tests/sfz1 basic tests/Unsorted/filter dynamic cutoff cc1 and channel after lpf_2p",
    "tests/sfz1 basic tests/Unsorted/filter keycenter",
    "tests/sfz1 basic tests/Unsorted/filter keytrack negative",
    "tests/sfz1 basic tests/Unsorted/filter keytrack",
    "tests/sfz1 basic tests/Unsorted/filter resonance",
    "tests/sfz1 basic tests/Unsorted/filter velocity tracking negative",
    "tests/sfz1 basic tests/Unsorted/filter velocity tracking",
    "tests/sfz1 basic tests/Unsorted/input controls bend",
    "tests/sfz1 basic tests/Unsorted/input controls midi cc",
    "tests/sfz1 basic tests/Unsorted/legato",
    "tests/sfz1 basic tests/Unsorted/loop marked without start and end",
    "tests/sfz1 basic tests/Unsorted/loop points from mono wav",
    "tests/sfz1 basic tests/Unsorted/loop points from stereo wav",
    "tests/sfz1 basic tests/Unsorted/loop points",
    "tests/sfz1 basic tests/Unsorted/loop_continuous",
    "tests/sfz1 basic tests/Unsorted/loop_sustain",
    "tests/sfz1 basic tests/Unsorted/multiple regions basic test",
    "tests/sfz1 basic tests/Unsorted/note delay multi",
    "tests/sfz1 basic tests/Unsorted/note delay",
    "tests/sfz1 basic tests/Unsorted/note names",
    "tests/sfz1 basic tests/Unsorted/offmode mode fast",
    "tests/sfz1 basic tests/Unsorted/offmode mode normal",
    "tests/sfz1 basic tests/Unsorted/on cc",
    "tests/sfz1 basic tests/Unsorted/one shot",
    "tests/sfz1 basic tests/Unsorted/organ",
    "tests/sfz1 basic tests/Unsorted/pan",
    "tests/sfz1 basic tests/Unsorted/pitch keycenter",
    "tests/sfz1 basic tests/Unsorted/pitch keytrack - inverted keyboard",
    "tests/sfz1 basic tests/Unsorted/pitch tune",
    "tests/sfz1 basic tests/Unsorted/pitch veltrack negative",
    "tests/sfz1 basic tests/Unsorted/pitch veltrack positive",
    "tests/sfz1 basic tests/Unsorted/random amp",
    "tests/sfz1 basic tests/Unsorted/random filter",
    "tests/sfz1 basic tests/Unsorted/random pitch",
    "tests/sfz1 basic tests/Unsorted/random",
    "tests/sfz1 basic tests/Unsorted/release trigger",
    "tests/sfz1 basic tests/Unsorted/rt",
    "tests/sfz1 basic tests/Unsorted/sample based on bpm",
    "tests/sfz1 basic tests/Unsorted/sample end",
    "tests/sfz1 basic tests/Unsorted/sequence",
    "tests/sfz1 basic tests/Unsorted/sw if down",
    "tests/sfz1 basic tests/Unsorted/sw if last",
    "tests/sfz1 basic tests/Unsorted/sw if up",
    "tests/sfz1 basic tests/Unsorted/sw previous",
    "tests/sfz1 basic tests/Unsorted/sync to host",
    "tests/sfz1 basic tests/Unsorted/width and position",
    "tests/sfz1 basic tests/Unsorted/xfade equal power test",
    "tests/sfz1 basic tests/Unsorted/xfade in on cc1",
    "tests/sfz1 basic tests/Unsorted/xfade out on cc1",
    "tests/sfz1 basic tests/Unsorted/xfade two layers on cc1 or cc2",
    "tests/sfz2 basic tests/00 - syntax/00 - syntax introduction",
    "tests/sfz2 basic tests/00 - syntax/01 - syntax note names",
    "tests/sfz2 basic tests/00 - syntax/01a - octave offset",
    "tests/sfz2 basic tests/00 - syntax/01b - control header",
    "tests/sfz2 basic tests/00 - syntax/02 - syntax keyb split",
    "tests/sfz2 basic tests/00 - syntax/03 - syntax two layers",
    "tests/sfz2 basic tests/00 - syntax/04 - syntax group",
    "tests/sfz2 basic tests/00 - syntax/05 - syntax comments",
    "tests/sfz2 basic tests/00 - syntax/06 - syntax key opcode",
    "tests/sfz2 basic tests/00 - syntax/07 - syntax special controls (random)",
    "tests/sfz2 basic tests/00 - syntax/08 - This is an extremely long name to test the display",
    "tests/sfz2 basic tests/00 - syntax/09 - unknown opcode",
    "tests/sfz2 basic tests/00 - syntax/10 - unknown opcode fx",
    "tests/sfz2 basic tests/00 - syntax/11 - unknown opcode curve",
    "tests/sfz2 basic tests/00 - syntax/20 - nothing",
    "tests/sfz2 basic tests/00 - syntax/21 - one region, no final CR",
    "tests/sfz2 basic tests/00 - syntax/22 - md5 test",
    "tests/sfz2 basic tests/01 - delay, offset/00 - region delay",
    "tests/sfz2 basic tests/01 - delay, offset/01 - region delay on cc",
    "tests/sfz2 basic tests/01 - delay, offset/02 - region delay on velocity",
    "tests/sfz2 basic tests/01 - delay, offset/03 - region delay on random",
    "tests/sfz2 basic tests/01 - delay, offset/04 - offset on cc",
    "tests/sfz2 basic tests/01 - delay, offset/05 - offset random",
    "tests/sfz2 basic tests/01 - delay, offset/06 - sample end",
    "tests/sfz2 basic tests/02 - input controls/00 - region select on keyboard",
    "tests/sfz2 basic tests/02 - input controls/01 - region select on channel",
    "tests/sfz2 basic tests/02 - input controls/02 - region select on midi cc",
    "tests/sfz2 basic tests/02 - input controls/03 - region select on bend",
    "tests/sfz2 basic tests/02 - input controls/04 - region select on sequence",
    "tests/sfz2 basic tests/02 - input controls/05 - region select on legato playing",
    "tests/sfz2 basic tests/02 - input controls/06 - region select on random",
    "tests/sfz2 basic tests/02 - input controls/07 - region select on sw if down",
    "tests/sfz2 basic tests/02 - input controls/08 - region select on sw if up",
    "tests/sfz2 basic tests/02 - input controls/09 - region select on sw if last",
    "tests/sfz2 basic tests/02 - input controls/10 - region select - sw default",
    "tests/sfz2 basic tests/02 - input controls/11 - region select on sw previous",
    "tests/sfz2 basic tests/02 - input controls/12 - region select on host tempo",
    "tests/sfz2 basic tests/02 - input controls/13 - quantize to host position",
    "tests/sfz2 basic tests/02 - input controls/14 - quantize to host position offset=1",
    "tests/sfz2 basic tests/02 - input controls/15 - multiple regions basic",
    "tests/sfz2 basic tests/02 - input controls/16 - region trigger on cc",
    "tests/sfz2 basic tests/02 - input controls/17 - region trigger start-stop on cc",
    "tests/sfz2 basic tests/02 - input controls/18 - region select on polyaft1",
    "tests/sfz2 basic tests/02 - input controls/19 - region select on polyaft2",
    "tests/sfz2 basic tests/03 - release triggers/00 - release trigger decay",
    "tests/sfz2 basic tests/03 - release triggers/01 - release trigger not on dead layer",
    "tests/sfz2 basic tests/03 - release triggers/02 - release trigger on dead layer",
    "tests/sfz2 basic tests/03 - release triggers/03 - release trigger not on sustain switch",
    "tests/sfz2 basic tests/03 - release triggers/04 - release trigger on sustain switch",
    "tests/sfz2 basic tests/03 - release triggers/05 - release trigger on sustain switch not on dead layer",
    "tests/sfz2 basic tests/03 - release triggers/06 - release trigger on sustain switch on dead layer",
    "tests/sfz2 basic tests/03 - release triggers/07 - release trigger simple test",
    "tests/sfz2 basic tests/03 - release triggers/08 - release trigger and key switches",
    "tests/sfz2 basic tests/04 - voice groups/01 - polyphony",
    "tests/sfz2 basic tests/04 - voice groups/02 - polyphony note self mask",
    "tests/sfz2 basic tests/04 - voice groups/03 - polyphony note no self mask",
    "tests/sfz2 basic tests/04 - voice groups/04 - exclusive regions bi",
    "tests/sfz2 basic tests/04 - voice groups/05 - exclusive regions uni",
    "tests/sfz2 basic tests/04 - voice groups/06 - exclusive regions cut one",
    "tests/sfz2 basic tests/04 - voice groups/07 - offmode mode fast",
    "tests/sfz2 basic tests/04 - voice groups/08 - offmode mode normal",
    "tests/sfz2 basic tests/04 - voice groups/09 - sustain switch on",
    "tests/sfz2 basic tests/04 - voice groups/10 - sustain switch off",
    "tests/sfz2 basic tests/04 - voice groups/11 - sustain switch on and off",
    "tests/sfz2 basic tests/04 - voice groups/12 - sostenuto switch on",
    "tests/sfz2 basic tests/04 - voice groups/13 - sostenuto switch off",
    "tests/sfz2 basic tests/04 - voice groups/14 - sustain and sostenuto switch off",
    "tests/sfz2 basic tests/04 - voice groups/15 - legato last note",
    "tests/sfz2 basic tests/04 - voice groups/16 - legato high note",
    "tests/sfz2 basic tests/04 - voice groups/17 - legato low note",
    "tests/sfz2 basic tests/04 - voice groups/18 - legato two zones",
    "tests/sfz2 basic tests/04 - voice groups/19 - legato two overlapping zones",
    "tests/sfz2 basic tests/04 - voice groups/20 - polyphony stealing (ARIA)",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/00 - pitch keycenter",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/01 - pitch keytrack",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/01a - pitch keytrack 100 cents",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/02 - pitch keytrack - inverted keyboard",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/03 - pitch veltrack positive",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/04 - pitch veltrack negative",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/05 - pitch on cc bipolar",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/06 - pitch on cc digital",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/07 - pitch on cc sawed",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/08 - pitch on cc tri-state",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/09 - pitch on cc smooth",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/10 - pitch on after",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/11 - pitch on random center",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/12 - pitch on random down",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/13 - pitch on random up",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/14 - pitch on velo",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/15 - pitch tune",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/20 - bend down and up",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/21 - bend two regions",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/22 - bend two regions smooth",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/23 - bend step octave",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/24 - bend step semi",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/25 - bend step up semi down octave",
    "tests/sfz2 basic tests/05 - pitch, pitch bend/26 - bend step whole",
    "tests/sfz2 basic tests/06 - decim, bitred/00 - decimator on cc",
    "tests/sfz2 basic tests/06 - decim, bitred/01 - decimator on cc smooth",
    "tests/sfz2 basic tests/06 - decim, bitred/02 - bit reducer on cc",
    "tests/sfz2 basic tests/06 - decim, bitred/03 - bit reducer on cc smooth",
    "tests/sfz2 basic tests/07 - noise/00 - noise mono",
    "tests/sfz2 basic tests/07 - noise/01 - noise stereo",
    "tests/sfz2 basic tests/07 - noise/02 - noise mono level on cc",
    "tests/sfz2 basic tests/07 - noise/03 - noise mono step on cc",
    "tests/sfz2 basic tests/07 - noise/04 - noise mono tone on cc",
    "tests/sfz2 basic tests/07 - noise/05 - noise mono hpf_1p",
    "tests/sfz2 basic tests/07 - noise/06 - noise stereo level on cc",
    "tests/sfz2 basic tests/07 - noise/07 - noise stereo step on cc",
    "tests/sfz2 basic tests/07 - noise/08 - noise stereo tone on cc",
    "tests/sfz2 basic tests/07 - noise/09 - noise stereo hpf_1p",
    "tests/sfz2 basic tests/08 - filters/00 - filter cutoff on cc smooth",
    "tests/sfz2 basic tests/08 - filters/01 - filter cutoff keycenter",
    "tests/sfz2 basic tests/08 - filters/02 - filter cutoff keytrack",
    "tests/sfz2 basic tests/08 - filters/03 - filter cutoff keytrack negative",
    "tests/sfz2 basic tests/08 - filters/04 - filter cutoff random",
    "tests/sfz2 basic tests/08 - filters/05 - filter cutoff velocity tracking",
    "tests/sfz2 basic tests/08 - filters/06 - filter cutoff velocity tracking negative",
    "tests/sfz2 basic tests/08 - filters/07 - cutoff as note names",
    "tests/sfz2 basic tests/08 - filters/10 - filter resonance",
    "tests/sfz2 basic tests/08 - filters/11 - filter resonance on cc",
    "tests/sfz2 basic tests/08 - filters/12 - filter resonance on cc smooth",
    "tests/sfz2 basic tests/08 - filters/13 - filter resonance random",
    "tests/sfz2 basic tests/08 - filters/20 - filter lpf_1p noise mono",
    "tests/sfz2 basic tests/08 - filters/21 - filter lpf_1p noise stereo",
    "tests/sfz2 basic tests/08 - filters/22 - filter hpf_1p noise mono",
    "tests/sfz2 basic tests/08 - filters/23 - filter hpf_1p noise stereo",
    "tests/sfz2 basic tests/08 - filters/24 - filter bpf_1p noise mono",
    "tests/sfz2 basic tests/08 - filters/25 - filter bpf_1p noise stereo",
    "tests/sfz2 basic tests/08 - filters/26 - filter brf_1p noise mono",
    "tests/sfz2 basic tests/08 - filters/27 - filter brf_1p noise stereo",
    "tests/sfz2 basic tests/08 - filters/28 - filter apf_1p noise mono",
    "tests/sfz2 basic tests/08 - filters/29 - filter apf_1p noise stereo",
    "tests/sfz2 basic tests/08 - filters/30 - filter lpf_2p noise mono",
    "tests/sfz2 basic tests/08 - filters/31 - filter lpf_2p noise stereo",
    "tests/sfz2 basic tests/08 - filters/32 - filter hpf_2p noise mono",
    "tests/sfz2 basic tests/08 - filters/33 - filter hpf_2p noise stereo",
    "tests/sfz2 basic tests/08 - filters/34 - filter bpf_2p noise mono",
    "tests/sfz2 basic tests/08 - filters/35 - filter bpf_2p noise stereo",
    "tests/sfz2 basic tests/08 - filters/36 - filter brf_2p noise mono",
    "tests/sfz2 basic tests/08 - filters/37 - filter brf_2p noise stereo",
    "tests/sfz2 basic tests/08 - filters/38 - filter spl_2p noise mono",
    "tests/sfz2 basic tests/08 - filters/39 - filter spl_2p noise stereo",
    "tests/sfz2 basic tests/08 - filters/40 - filter lpf_4p noise mono",
    "tests/sfz2 basic tests/08 - filters/41 - filter lpf_4p noise stereo",
    "tests/sfz2 basic tests/08 - filters/42 - filter hpf_4p noise mono",
    "tests/sfz2 basic tests/08 - filters/43 - filter hpf_4p noise stereo",
    "tests/sfz2 basic tests/08 - filters/50 - filter lpf_6p noise mono",
    "tests/sfz2 basic tests/08 - filters/51 - filter lpf_6p noise stereo",
    "tests/sfz2 basic tests/08 - filters/52 - filter hpf_6p noise mono",
    "tests/sfz2 basic tests/08 - filters/53 - filter hpf_6p noise stereo",
    "tests/sfz2 basic tests/08 - filters/60 - filter comb noise mono",
    "tests/sfz2 basic tests/08 - filters/61 - filter pink noise mono",
    "tests/sfz2 basic tests/08 - filters/62 - filter pink noise stereo",
    "tests/sfz2 basic tests/08 - filters/70 - filter lpf_1p sweep mono",
    "tests/sfz2 basic tests/08 - filters/71 - filter lpf_1p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/72 - filter hpf_1p sweep mono",
    "tests/sfz2 basic tests/08 - filters/73 - filter hpf_1p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/74 - filter bpf_1p sweep mono",
    "tests/sfz2 basic tests/08 - filters/75 - filter bpf_1p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/76 - filter brf_1p sweep mono",
    "tests/sfz2 basic tests/08 - filters/77 - filter brf_1p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/78 - filter apf_1p sweep mono",
    "tests/sfz2 basic tests/08 - filters/79 - filter apf_1p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/80 - filter lpf_2p sweep mono",
    "tests/sfz2 basic tests/08 - filters/81 - filter lpf_2p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/82 - filter hpf_2p sweep mono",
    "tests/sfz2 basic tests/08 - filters/83 - filter hpf_2p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/84 - filter bpf_2p sweep mono",
    "tests/sfz2 basic tests/08 - filters/85 - filter bpf_2p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/86 - filter brf_2p sweep mono",
    "tests/sfz2 basic tests/08 - filters/87 - filter brf_2p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/90 - filter lpf_4p sweep mono",
    "tests/sfz2 basic tests/08 - filters/91 - filter lpf_4p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/92 - filter hpf_4p sweep mono",
    "tests/sfz2 basic tests/08 - filters/93 - filter hpf_4p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/94 - filter lpf_6p sweep mono",
    "tests/sfz2 basic tests/08 - filters/95 - filter lpf_6p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/96 - filter hpf_6p sweep mono",
    "tests/sfz2 basic tests/08 - filters/97 - filter hpf_6p sweep stereo",
    "tests/sfz2 basic tests/08 - filters/98 - filter comb sweep mono",
    "tests/sfz2 basic tests/08 - filters/99 - filter cutoff on polyaft",
    "tests/sfz2 basic tests/09 - drive/00 - drive mono",
    "tests/sfz2 basic tests/09 - drive/01 - drive stereo",
    "tests/sfz2 basic tests/09 - drive/02 - drive mono on cc",
    "tests/sfz2 basic tests/09 - drive/03 - drive stereo on cc",
    "tests/sfz2 basic tests/09 - drive/04 - drive shape on cc smooth ",
    "tests/sfz2 basic tests/09 - drive/05 - drive tone on cc smooth ",
    "tests/sfz2 basic tests/09 - drive/06 - drive on velocity",
    "tests/sfz2 basic tests/09 - drive/07 - drive on after",
    "tests/sfz2 basic tests/10 - eq/00 - eq1 dynamic",
    "tests/sfz2 basic tests/10 - eq/01 - eq2 dynamic",
    "tests/sfz2 basic tests/10 - eq/03 - eq3 dynamic",
    "tests/sfz2 basic tests/10 - eq/04 - eq three bands mono",
    "tests/sfz2 basic tests/10 - eq/05 - eq three bands stereo",
    "tests/sfz2 basic tests/10 - eq/06 - formants",
    "tests/sfz2 basic tests/11 - compressor, gate/00 - compressor test mono",
    "tests/sfz2 basic tests/11 - compressor, gate/01 - compressor test stereo",
    "tests/sfz2 basic tests/11 - compressor, gate/02 - compressor test link",
    "tests/sfz2 basic tests/11 - compressor, gate/03 - gate test mono",
    "tests/sfz2 basic tests/11 - compressor, gate/04 - gate test stereo",
    "tests/sfz2 basic tests/11 - compressor, gate/05 - gate test link",
    "tests/sfz2 basic tests/11 - compressor, gate/06 - gate on cc",
    "tests/sfz2 basic tests/12 - amplifier/00 - volume",
    "tests/sfz2 basic tests/12 - amplifier/01 - volume on cc smooth",
    "tests/sfz2 basic tests/12 - amplifier/02 - volume on random",
    "tests/sfz2 basic tests/12 - amplifier/03 - amp velo tracking",
    "tests/sfz2 basic tests/12 - amplifier/04 - amp velo tracking negative",
    "tests/sfz2 basic tests/12 - amplifier/05 - amp key tracking",
    "tests/sfz2 basic tests/12 - amplifier/06 - amp key tracking negative",
    "tests/sfz2 basic tests/12 - amplifier/07 - amp velo curve",
    "tests/sfz2 basic tests/12 - amplifier/08 - phase normal",
    "tests/sfz2 basic tests/12 - amplifier/09 - phase inverted",
    "tests/sfz2 basic tests/12 - amplifier/10 - phase cancel",
    "tests/sfz2 basic tests/12 - amplifier/11 - pan",
    "tests/sfz2 basic tests/12 - amplifier/12 - pan keytrack",
    "tests/sfz2 basic tests/12 - amplifier/13 - pan keycenter c3",
    "tests/sfz2 basic tests/12 - amplifier/14 - pan cc73 unipolar",
    "tests/sfz2 basic tests/12 - amplifier/15 - pan cc73 bipolar",
    "tests/sfz2 basic tests/12 - amplifier/16 - pan on cc smooth",
    "tests/sfz2 basic tests/12 - amplifier/17 - pan on random",
    "tests/sfz2 basic tests/12 - amplifier/18 - pan veltrack",
    "tests/sfz2 basic tests/12 - amplifier/19 - pan veltrack negative",
    "tests/sfz2 basic tests/12 - amplifier/20 - width",
    "tests/sfz2 basic tests/12 - amplifier/21 - width on cc",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/00 - amp eg delay",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/01 - amp eg attack",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/02 - amp eg hold",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/03 - amp eg decay",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/04 - amp eg release",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/05 - amp eg all",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/06 - amp eg attack random",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/07 - amp eg cc 20 to 26",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/08 - amp eg delay on velocity",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/09 - amp eg attack on velocity",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/10 - amp eg hold on velocity",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/11 - amp eg decay on velocity",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/12 - amp eg release on velocity",
    "tests/sfz2 basic tests/13 - amplifier eg (main)/13 - amp eg on release trigger",
    "tests/sfz2 basic tests/14 - crossfade/00 - fade in on cc1",
    "tests/sfz2 basic tests/14 - crossfade/01 - fade out on cc1",
    "tests/sfz2 basic tests/14 - crossfade/02 - xfade on cc equal gaint",
    "tests/sfz2 basic tests/14 - crossfade/03 - xfade on cc equal power",
    "tests/sfz2 basic tests/14 - crossfade/04 - xfade two layers on cc1 or cc2",
    "tests/sfz2 basic tests/14 - crossfade/05 - fade in and out on keyboard",
    "tests/sfz2 basic tests/14 - crossfade/06 - xfade on keyboard - equal gain",
    "tests/sfz2 basic tests/14 - crossfade/07 - xfade on keyboard - equal power",
    "tests/sfz2 basic tests/14 - crossfade/08 - xfade on velocity - equal gain",
    "tests/sfz2 basic tests/14 - crossfade/09 - xfade on velocity - equal power",
    "tests/sfz2 basic tests/14 - crossfade/10 - xfade_edgecase0",
    "tests/sfz2 basic tests/14 - crossfade/11 - xfade_edgecase1",
    "tests/sfz2 basic tests/14 - crossfade/12 - xfade_edgecase2",
    "tests/sfz2 basic tests/14 - crossfade/13 - xfade_edgecase3",
    "tests/sfz2 basic tests/14 - crossfade/99 - xfade_4oscs (ARIA)",
    "tests/sfz2 basic tests/15 - effect sends/00 - effect sends (turn fx on)",
    "tests/sfz2 basic tests/15 - effect sends/01 - DP_Sexy hidden 16-pole filter model",
    "tests/sfz2 basic tests/15 - effect sends/02 - chap17l",
    "tests/sfz2 basic tests/16 - loops/00 - loop points from mono wav",
    "tests/sfz2 basic tests/16 - loops/01 - loop points from stereo wav",
    "tests/sfz2 basic tests/16 - loops/03 - loop points defined",
    "tests/sfz2 basic tests/16 - loops/04 - loop marked without start and end",
    "tests/sfz2 basic tests/16 - loops/05 - loop count defined",
    "tests/sfz2 basic tests/16 - loops/06 - loop direction defined (forward)",
    "tests/sfz2 basic tests/16 - loops/07 - loop direction defined (backward)",
    "tests/sfz2 basic tests/16 - loops/08 - loop direction defined (alternate)",
    "tests/sfz2 basic tests/16 - loops/09 - loop tune",
    "tests/sfz2 basic tests/16 - loops/10 - loop_continuous",
    "tests/sfz2 basic tests/16 - loops/11 - loop_sustain",
    "tests/sfz2 basic tests/16 - loops/12 - one shot",
    "tests/sfz2 basic tests/16 - loops/13 - reverse",
    "tests/sfz2 basic tests/16 - loops/14 - reverse offset",
    "tests/sfz2 basic tests/16 - loops/15 - sample count",
    "tests/sfz2 basic tests/16 - loops/16 - reverse loop",
    "tests/sfz2 basic tests/16 - loops/17 - reverse loop sine",
    "tests/sfz2 basic tests/16 - loops/18 - reverse on release trigger",
    "tests/sfz2 basic tests/16 - loops/19 - sample count, reverse and loops",
    "tests/sfz2 basic tests/16 - loops/20 - loop start on cc",
    "tests/sfz2 basic tests/17 - LFO/00 - lfo01_freq",
    "tests/sfz2 basic tests/17 - LFO/01 - lfo01_freq_oncc",
    "tests/sfz2 basic tests/17 - LFO/02 - lfo01_freq_lfo",
    "tests/sfz2 basic tests/17 - LFO/03 - lfo01_fade",
    "tests/sfz2 basic tests/17 - LFO/04 - lfo01_count",
    "tests/sfz2 basic tests/17 - LFO/05 - lfo01_inter",
    "tests/sfz2 basic tests/17 - LFO/06 - lfo01_phase",
    "tests/sfz2 basic tests/17 - LFO/07 - lfo01_delay",
    "tests/sfz2 basic tests/17 - LFO/08 - lfo01_step",
    "tests/sfz2 basic tests/17 - LFO/09 - lfo01_step_oncc smooth",
    "tests/sfz2 basic tests/17 - LFO/10 - lfo01_step_oncc",
    "tests/sfz2 basic tests/17 - LFO/20 - lfo01_pitch",
    "tests/sfz2 basic tests/17 - LFO/21 - lfo01_pitch_oncc",
    "tests/sfz2 basic tests/17 - LFO/22 - lfo01_decim",
    "tests/sfz2 basic tests/17 - LFO/23 - lfo01_decim_oncc",
    "tests/sfz2 basic tests/17 - LFO/24 - lfo01_bitred",
    "tests/sfz2 basic tests/17 - LFO/25 - lfo01_bitred_oncc",
    "tests/sfz2 basic tests/17 - LFO/26 - lfo01_noiselevel",
    "tests/sfz2 basic tests/17 - LFO/27 - lfo01_noiselevel_oncc",
    "tests/sfz2 basic tests/17 - LFO/28 - lfo01_noisestep",
    "tests/sfz2 basic tests/17 - LFO/29 - lfo01_noisestep_oncc",
    "tests/sfz2 basic tests/17 - LFO/30 - lfo01_noisetone",
    "tests/sfz2 basic tests/17 - LFO/31 - lfo01_noisetone_oncc",
    "tests/sfz2 basic tests/17 - LFO/32 - lfo01_cutoff",
    "tests/sfz2 basic tests/17 - LFO/33 - lfo01_cutoff_oncc",
    "tests/sfz2 basic tests/17 - LFO/34 - lfo01_resonance",
    "tests/sfz2 basic tests/17 - LFO/35 - lfo01_resonance_oncc",
    "tests/sfz2 basic tests/17 - LFO/36 - lfo01_drive",
    "tests/sfz2 basic tests/17 - LFO/37 - lfo01_drive_oncc",
    "tests/sfz2 basic tests/17 - LFO/38 - lfo01_eq1freq",
    "tests/sfz2 basic tests/17 - LFO/39 - lfo01_eq1freq_oncc",
    "tests/sfz2 basic tests/17 - LFO/40 - lfo01_eq1bw",
    "tests/sfz2 basic tests/17 - LFO/41 - lfo01_eq1bw_oncc",
    "tests/sfz2 basic tests/17 - LFO/42 - lfo01_eq1gaiin",
    "tests/sfz2 basic tests/17 - LFO/43 - lfo01_eq1gain_oncc",
    "tests/sfz2 basic tests/17 - LFO/44 - lfo01_eq2bw",
    "tests/sfz2 basic tests/17 - LFO/45 - lfo01_eq2freq",
    "tests/sfz2 basic tests/17 - LFO/46 - lfo01_eq2gaiin",
    "tests/sfz2 basic tests/17 - LFO/47 - lfo01_eq3bw",
    "tests/sfz2 basic tests/17 - LFO/48 - lfo01_eq3freq",
    "tests/sfz2 basic tests/17 - LFO/49 - lfo01_eq3gain",
    "tests/sfz2 basic tests/17 - LFO/50 - lfo01 all eqfreq _oncc",
    "tests/sfz2 basic tests/17 - LFO/51 - lfo01_volume",
    "tests/sfz2 basic tests/17 - LFO/52 - lfo01_volume_oncc",
    "tests/sfz2 basic tests/17 - LFO/53 - lfo01_pan",
    "tests/sfz2 basic tests/17 - LFO/54 - lfo01_pan_oncc",
    "tests/sfz2 basic tests/17 - LFO/55 - lfo01_width",
    "tests/sfz2 basic tests/17 - LFO/56 - lfo01_width_oncc",
    "tests/sfz2 basic tests/17 - LFO/57 - lfo_feedback",
    "tests/sfz2 basic tests/17 - LFO/58 - lfo01_freq_lfo_dual",
    "tests/sfz2 basic tests/17 - LFO/60 - multi lfo basic test",
    "tests/sfz2 basic tests/18 - EG/02 - eg01_shape",
    "tests/sfz2 basic tests/18 - EG/03 - eg01_loop",
    "tests/sfz2 basic tests/18 - EG/04 - eg01_loop count",
    "tests/sfz2 basic tests/18 - EG/10 - eg01_pitch",
    "tests/sfz2 basic tests/18 - EG/11 - eg01_pitch_oncc",
    "tests/sfz2 basic tests/18 - EG/12 - eg01_decim",
    "tests/sfz2 basic tests/18 - EG/13 - eg01_decim_oncc",
    "tests/sfz2 basic tests/18 - EG/14 - eg01_bitred",
    "tests/sfz2 basic tests/18 - EG/15 - eg01_bitred_oncc",
    "tests/sfz2 basic tests/18 - EG/16 - eg01_noiselevel",
    "tests/sfz2 basic tests/18 - EG/17 - eg01_noiselevel_oncc",
    "tests/sfz2 basic tests/18 - EG/18 - eg01_noisestep",
    "tests/sfz2 basic tests/18 - EG/19 - eg01_noisestep_oncc",
    "tests/sfz2 basic tests/18 - EG/20 - eg01_noisetone",
    "tests/sfz2 basic tests/18 - EG/21 - eg01_noisetone_oncc",
    "tests/sfz2 basic tests/18 - EG/22 - eg01_cutoff",
    "tests/sfz2 basic tests/18 - EG/23 - eg01_cutoff_oncc",
    "tests/sfz2 basic tests/18 - EG/24 - eg01_resonance",
    "tests/sfz2 basic tests/18 - EG/25 - eg01_resonance_oncc",
    "tests/sfz2 basic tests/18 - EG/26 - eg01_drive",
    "tests/sfz2 basic tests/18 - EG/27 - eg01_drive_oncc",
    "tests/sfz2 basic tests/18 - EG/28 - eg01_eq1freq",
    "tests/sfz2 basic tests/18 - EG/29 - eg01_eq1freq_oncc",
    "tests/sfz2 basic tests/18 - EG/30 - eg01_eq1bw",
    "tests/sfz2 basic tests/18 - EG/31 - eg01_eq1bw_oncc",
    "tests/sfz2 basic tests/18 - EG/32 - eg01_eq1gain",
    "tests/sfz2 basic tests/18 - EG/33 - eg01_eq1gain_oncc",
    "tests/sfz2 basic tests/18 - EG/34 - eg01_eq2freq",
    "tests/sfz2 basic tests/18 - EG/36 - eg01_eq2bw",
    "tests/sfz2 basic tests/18 - EG/38 - eg01_eq2gain",
    "tests/sfz2 basic tests/18 - EG/40 - eg01_eq3freq",
    "tests/sfz2 basic tests/18 - EG/42 - eg01_eq3bw",
    "tests/sfz2 basic tests/18 - EG/44 - eg01_eq3gain",
    "tests/sfz2 basic tests/18 - EG/46 - eg01 all eq freq _oncc",
    "tests/sfz2 basic tests/18 - EG/48 - eg01 all eq bw _oncc",
    "tests/sfz2 basic tests/18 - EG/50 - eg01 all eq gain _oncc",
    "tests/sfz2 basic tests/18 - EG/51 - eg01_volume",
    "tests/sfz2 basic tests/18 - EG/52 - eg01_volume_oncc",
    "tests/sfz2 basic tests/18 - EG/53 - eg01_pan",
    "tests/sfz2 basic tests/18 - EG/54 - eg01_pan_oncc",
    "tests/sfz2 basic tests/18 - EG/55 - eg01_width",
    "tests/sfz2 basic tests/18 - EG/56 - eg01_width_oncc",
    "tests/sfz2 basic tests/18 - EG/57 - eg01_freq_lfo01",
    "tests/sfz2 basic tests/18 - EG/58 - eg01_depth_lfo01",
    "tests/sfz2 basic tests/18 - EG/59 - eg01_depthadd_lfo01",
    "tests/sfz2 basic tests/18 - EG/60 - eg01_depthadd_lfo01_test2",
    "tests/sfz2 basic tests/18 - EG/61 - eg01_ampeg",
    "tests/sfz2 basic tests/18 - EG/99 - eg01_pitch (tool generated)",
    "tests/sfz2 basic tests/19 - glide/00 - glidetime pitch_davidv",
    "tests/sfz2 basic tests/19 - glide/00 - glidetime pitch",
    "tests/sfz2 basic tests/19 - glide/01 - glidespeed pitch",
    "tests/sfz2 basic tests/19 - glide/02 - glidespeed time on cc pitch",
    "tests/sfz2 basic tests/19 - glide/03 - glide for 2 points eg pitch",
    "tests/sfz2 basic tests/19 - glide/04 - glide for 2 points level on cc pitch",
    "tests/sfz2 basic tests/20 - envelope follower/00 - envelope follower pitch",
    "tests/sfz2 basic tests/20 - envelope follower/01 - envelope follower filter",
]

SFZ = [
    {
        "sfz": f"{BASE_PATH}{REGRESSION_TEST_PATH}{SFZ_PATH}{file}{SFZ_FILE}",
        "xml": f"{BASE_PATH}{REGRESSION_TEST_PATH}{XML_PATH}{file}{XML_FILE}",
    }
    for file in SFZ_FILES
]
